// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SearchEngineProject.Persistence;

#nullable disable

namespace SearchEngine.Persistence.Persistence.Migrations
{
    [DbContext(typeof(SearchEngineContext))]
    [Migration("20250427232527_quicktest")]
    partial class quicktest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("SearchEngineProject.Persistence.Entities.DocumentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("SearchEngineProject.Persistence.Entities.DocumentTokenEntity", b =>
                {
                    b.Property<int>("DocumentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EndOffset")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StartOffset")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("DocumentId", "Position");

                    b.ToTable("DocumentTokens");
                });

            modelBuilder.Entity("SearchEngineProject.Persistence.Entities.DocumentTokenEntity", b =>
                {
                    b.HasOne("SearchEngineProject.Persistence.Entities.DocumentEntity", "Document")
                        .WithMany("Tokens")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("SearchEngineProject.Persistence.Entities.DocumentEntity", b =>
                {
                    b.Navigation("Tokens");
                });
#pragma warning restore 612, 618
        }
    }
}
