// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SearchEngine.Persistence;

#nullable disable

namespace SearchEngine.Persistence.Persistence.Migrations
{
    [DbContext(typeof(SearchEngineContext))]
    partial class SearchEngineContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("SearchEngine.Persistence.Entities.DocumentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("SearchEngine.Persistence.Entities.DocumentTermEntity", b =>
                {
                    b.Property<int>("DocumentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Term")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PositionsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DocumentId", "Term");

                    b.ToTable("DocumentTerms");
                });

            modelBuilder.Entity("SearchEngine.Persistence.Entities.DocumentTermEntity", b =>
                {
                    b.HasOne("SearchEngine.Persistence.Entities.DocumentEntity", "Document")
                        .WithMany("Terms")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("SearchEngine.Persistence.Entities.DocumentEntity", b =>
                {
                    b.Navigation("Terms");
                });
#pragma warning restore 612, 618
        }
    }
}
